name: eventium-memory
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: In-memory implementations for eventium
description: |
  Eventium-memory provides in-memory implementations of event stores and projection caches
  for the Eventium event sourcing framework. This package is ideal for development, testing, and prototyping
  event-sourced applications without requiring external dependencies like databases. All data is stored in
  STM-based concurrent data structures for thread-safe access.
stability: experimental
category: Database,Eventsourcing
license: MIT
license-file: LICENSE.md

github: aleks-sidorenko/eventium

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - eventium-core >= 0.1.0 && < 0.2.0
  - containers >= 0.6 && < 0.8
  - mtl >= 2.2 && < 2.4
  - safe >= 0.3 && < 0.4
  - stm >= 2.5 && < 2.6

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventium-testkit
    build-tools:
      - hspec-discover
