name: eventium-sql-common
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: Common library for SQL event stores
description: |
  Eventium-sql-common provides shared utilities and abstractions for SQL-based event stores.
  It includes Persistent entity definitions, JSON serialization helpers, and common database
  operations used by eventium-postgresql and eventium-sqlite. This package eliminates code
  duplication between different SQL backend implementations and provides a consistent interface
  for SQL-based event sourcing.
stability: experimental
category: Database,Eventsourcing
license: MIT
license-file: LICENSE.md

github: aleks-sidorenko/eventium

dependencies:
  - base >= 4.9 && < 5
  - eventium-core >= 0.1.0 && < 0.2.0

  - aeson >= 1.5 && < 2.3
  - bytestring >= 0.10 && < 0.13
  - mtl >= 2.2 && < 2.4
  - persistent >= 2.13 && < 2.15
  - persistent-template >= 2.12 && < 2.13
  - text >= 1.2 && < 2.2
  - time >= 1.9 && < 1.14
  - uuid >= 1.3 && < 1.4

library:
  source-dirs:
    - src
  ghc-options: -Wall
