name: eventium-postgresql
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: Postgres implementations for eventium
description: |
  Eventium-postgresql provides a PostgreSQL-based event store implementation for the Eventium event
  sourcing framework. It uses the Persistent library for type-safe database access and provides
  efficient event storage and retrieval with support for aggregate streams, event versioning, and
  optimistic concurrency control. This is a production-ready backend for event-sourced applications.
stability: experimental
category: Database,Eventsourcing,PostgreSQL
license: MIT
license-file: LICENSE.md

github: aleks-sidorenko/eventium

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - eventium-core >= 0.1.0 && < 0.2.0
  - eventium-sql-common >= 0.1.0 && < 0.2.0

  - aeson >= 1.5 && < 2.3
  - bytestring >= 0.10 && < 0.13
  - mtl >= 2.2 && < 2.4
  - persistent >= 2.13 && < 2.15
  - text >= 1.2 && < 2.2

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventium-testkit
      - persistent-postgresql
      - utf8-string
    build-tools:
      - hspec-discover
