name: eventium-sqlite
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: SQLite implementations for eventium
description: |
  Eventium-sqlite provides a SQLite-based event store implementation for the Eventium event sourcing
  framework. It uses the Persistent library for type-safe database access and provides efficient event
  storage and retrieval with support for aggregate streams, event versioning, and optimistic concurrency
  control. This backend is ideal for single-process applications, embedded systems, and scenarios where
  a lightweight database is preferred.
stability: experimental
category: Database,Eventsourcing,SQLite
license: MIT
license-file: LICENSE.md

github: aleks-sidorenko/eventium

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - eventium-core >= 0.1.0 && < 0.2.0
  - eventium-sql-common >= 0.1.0 && < 0.2.0

  - aeson >= 1.5 && < 2.3
  - bytestring >= 0.10 && < 0.13
  - mtl >= 2.2 && < 2.4
  - persistent >= 2.13 && < 2.15
  - text >= 1.2 && < 2.2
  - uuid >= 1.3 && < 1.4

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventium-test-helpers
      - persistent-sqlite
    build-tools:
      - hspec-discover
