name: eventium-testkit
version: "0.1.0"
maintainer: Alexander Sidorenko
synopsis: Testing utilities for eventium
description: |
  Eventium-testkit provides common testing utilities and helper functions for testing Eventium-based
  applications. It includes utilities for event store testing, serialization testing, and common test fixtures
  that are shared across the Eventium test suite. This package helps reduce code duplication in tests and
  provides a consistent testing interface.
stability: experimental
category: Database,Eventsourcing
license: MIT
license-file: LICENSE.md

github: aleks-sidorenko/eventium

dependencies:
  - base >= 4.9 && < 5
  - eventium-core >= 0.1.0 && < 0.2.0

  - aeson >= 1.5 && < 2.3
  - aeson-casing >= 0.2 && < 0.3
  - extra >= 1.7 && < 1.8
  - hspec >= 2.8 && < 2.12
  - monad-logger >= 0.3 && < 0.4
  - text >= 1.2 && < 2.2

library:
  source-dirs:
    - src
  ghc-options: -Wall
